// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Models;

#nullable disable

namespace Movies.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20240223072544_second2")]
    partial class second2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Movies.Models.Category", b =>
                {
                    b.Property<int>("Mission07_CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mission07_Category")
                        .HasColumnType("TEXT");

                    b.HasKey("Mission07_CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Mission07_CategoryId = 1,
                            Mission07_Category = "Miscellaneous"
                        },
                        new
                        {
                            Mission07_CategoryId = 2,
                            Mission07_Category = "Drama"
                        },
                        new
                        {
                            Mission07_CategoryId = 3,
                            Mission07_Category = "Television"
                        },
                        new
                        {
                            Mission07_CategoryId = 4,
                            Mission07_Category = "Horror/Suspense"
                        },
                        new
                        {
                            Mission07_CategoryId = 5,
                            Mission07_Category = "Comedy"
                        },
                        new
                        {
                            Mission07_CategoryId = 6,
                            Mission07_Category = "Family"
                        },
                        new
                        {
                            Mission07_CategoryId = 7,
                            Mission07_Category = "Action/Adventure"
                        },
                        new
                        {
                            Mission07_CategoryId = 8,
                            Mission07_Category = "VHS"
                        });
                });

            modelBuilder.Entity("Movies.Models.Movie", b =>
                {
                    b.Property<int>("Mission06_MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CopiedToPlex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mission06_Director")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Mission06_Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mission06_Lent_To")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mission06_Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mission06_Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mission06_Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mission06_Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mission07_CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Mission06_MovieId");

                    b.HasIndex("Mission07_CategoryId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Movies.Models.Movie", b =>
                {
                    b.HasOne("Movies.Models.Category", "Mission07_Category")
                        .WithMany()
                        .HasForeignKey("Mission07_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission07_Category");
                });
#pragma warning restore 612, 618
        }
    }
}
